server {
    listen 8091;
    location / {
        root /opt/romm-stream;
        index phone.html;
    }
    location /hls {
        alias /opt/romm-stream/hls;
        add_header Access-Control-Allow-Origin *;
        add_header Cache-Control no-cache;
        types { application/vnd.apple.mpegurl m3u8; video/mp2t ts; }
    }
    location /emu {
        alias /opt/romm-stream/emulatorjs;
        add_header Access-Control-Allow-Origin *;
    }
    location /roms {
        alias /mnt/usb1/roms;
        add_header Access-Control-Allow-Origin *;
    }
    location /api/ {
        proxy_pass http://127.0.0.1:8090;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }
}
